version: '3.5'
services:
### adds xdebug
  xdebug:
    container_name: app_xdebug
    build:
      context: docker/php
      target: xdebugPhp81
    environment:
      TZ: "Europe/Berlin"
    working_dir: "/var/www"
    ports:
      - 9001:9001
    volumes:
      - ${PROJECT_PATH}:/app
      - ./docker/php/xdebug-fpm.conf:/usr/local/etc/php-fpm.d/zz-xdebug.conf
### end xdebug

### nginx
  webserver:
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - xdebug
### end nginx

### adds nodejs for development
#  nodejs:
#    image: node:lts-alpine3.17
#    container_name: app_node
#    working_dir: /home/node/app
#    ports:
#      - "5173:5173"
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - ${PROJECT_PATH}:/home/node/app
#    command: npm run dev #vite build --watch ### yarn encore dev watch
### end nodejs

### composer for development
  composer:
    build:
      context: docker/php
      target: composerPhp81
    container_name: app_composer
    volumes:
      - ${PROJECT_PATH}:/app
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    command: composer update    ### composer update is mostly used in the 'development' phase, to upgrade our project packages.

  ### adds mailhog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: app_mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 # yes it is mailhog:1025 in symfony parameters/env
      - 8025:8025 # web ui
### ends mailhog
